[cp-contest]
type = "folder"
name = "cp-contest"
root = "{{ name }}"
folder = "cp-contest-template"

[cmake-project]
type = "folder"
name = "cmake-project"
root = "{{ project_name }}"
folder = "cmake-project-template"

[cp-problem]
type = "file"
name = "cp-problem"
root = "{{ name }}.cpp"
folder = "cp-problem-template"

[conanfile]
type = "file"
name = "conanfile"
root = "conanfile.txt"
folder = "conanfile-template"
name_param_optional = true

[cmake-mult-exec]
type = "folder"
name = "cmake-mult-exec"
root = "{{ name }}"
folder = "cmake-mult-exec-template"

[aoc-year]
type = "folder"
name = "aoc-year"
root = "{{ name }}"
folder = "aoc-year-template"

[aoc-day]
type = "folder"
name = "aoc-day"
root = "{{ name }}"
folder = "aoc-day-template"
